[providers]
providers = ["node"]

[phases.setup]
nixPkgs = ["curl"]
cmds = [
  "curl -L https://raw.githubusercontent.com/jcarbonnell/rindexer/main/install.sh | bash"
]

[phases.build]
cmds = [
  "echo 'Rindexer ready'"
]

[start]
cmd = "$HOME/.rindexer/bin/rindexer start all"